export enum TEMPLATES {
  GENERAL = 'general',
  PERSONAL = 'personal',
  SOCIAL = 'social',
  OWN = 'own',
  NO = 'no',
}

export enum PLANS {
  SUBSCRIPTION = 'subscription',
  MIN = 'minimal',
  MAX = 'maximal',
  TRIAL = 'trial',
}

export enum COLLEGE_DETAILS_TYPE {
  CONTACTS = 'contacts',
  SOCIALS = 'socials',
  QUESTIONNAIRE = 'Questionnaire',
  CAMPS = 'camps',
  INFO = 'info',
}

export const STATES = [
  { name: 'Alabama', abbreviation: 'AL' },
  { name: 'Alaska', abbreviation: 'AK' },
  { name: 'Arizona', abbreviation: 'AZ' },
  { name: 'Arkansas', abbreviation: 'AR' },
  { name: 'California', abbreviation: 'CA' },
  { name: 'Colorado', abbreviation: 'CO' },
  { name: 'Connecticut', abbreviation: 'CT' },
  { name: 'Delaware', abbreviation: 'DE' },
  { name: 'Florida', abbreviation: 'FL' },
  { name: 'Georgia', abbreviation: 'GA' },
  { name: 'Hawaii', abbreviation: 'HI' },
  { name: 'Idaho', abbreviation: 'ID' },
  { name: 'Illinois', abbreviation: 'IL' },
  { name: 'Indiana', abbreviation: 'IN' },
  { name: 'Iowa', abbreviation: 'IA' },
  { name: 'Kansas', abbreviation: 'KS' },
  { name: 'Kentucky', abbreviation: 'KY' },
  { name: 'Louisiana', abbreviation: 'LA' },
  { name: 'Maine', abbreviation: 'ME' },
  { name: 'Maryland', abbreviation: 'MD' },
  { name: 'Massachusetts', abbreviation: 'MA' },
  { name: 'Michigan', abbreviation: 'MI' },
  { name: 'Minnesota', abbreviation: 'MN' },
  { name: 'Mississippi', abbreviation: 'MS' },
  { name: 'Missouri', abbreviation: 'MO' },
  { name: 'Montana', abbreviation: 'MT' },
  { name: 'Nebraska', abbreviation: 'NE' },
  { name: 'Nevada', abbreviation: 'NV' },
  { name: 'New Hampshire', abbreviation: 'NH' },
  { name: 'New Jersey', abbreviation: 'NJ' },
  { name: 'New Mexico', abbreviation: 'NM' },
  { name: 'New York', abbreviation: 'NY' },
  { name: 'North Carolina', abbreviation: 'NC' },
  { name: 'North Dakota', abbreviation: 'ND' },
  { name: 'Ohio', abbreviation: 'OH' },
  { name: 'Oklahoma', abbreviation: 'OK' },
  { name: 'Oregon', abbreviation: 'OR' },
  { name: 'Pennsylvania', abbreviation: 'PA' },
  { name: 'Rhode Island', abbreviation: 'RI' },
  { name: 'South Carolina', abbreviation: 'SC' },
  { name: 'South Dakota', abbreviation: 'SD' },
  { name: 'Tennessee', abbreviation: 'TN' },
  { name: 'Texas', abbreviation: 'TX' },
  { name: 'Utah', abbreviation: 'UT' },
  { name: 'Vermont', abbreviation: 'VT' },
  { name: 'Virginia', abbreviation: 'VA' },
  { name: 'Washington', abbreviation: 'WA' },
  { name: 'West Virginia', abbreviation: 'WV' },
  { name: 'Wisconsin', abbreviation: 'WI' },
  { name: 'Wyoming', abbreviation: 'WY' },
];

export const ALPHABET = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z',
];

export const SPORTS = [
  'football',
  'field hockey',
  'basketball mens',
  'basketball womens',
  'baseball',
  'softball',
  'soccer mens',
  'soccer womens',
  'lacrosse mens',
  'lacrosse womens',
  'golf mens',
  'golf womens',
  'track & field mens',
  'track & field womens',
  'cross country mens',
  'cross country womens',
  'volleyball mens',
  'volleyball womens',
  'rowing mens',
  'rowing womens',
  'wrestling',
  'bowling womens',
  'ice hockey mens',
  'ice hockey womens',
  'tennis mens',
  'tennis womens',
  'swimming & diving mens',
  'swimming & diving womens',
  'gymnastics mens',
  'gymnastics womens',
  'water polo mens',
  'water polo womens',
];

export const SPORTS_POSITIONS = {
  football: [
    'quarterback',
    'running back',
    'wide receiver',
    'tight end',
    'center',
    'guard',
    'tackle',
    'defensive tackle',
    'defensive end',
    'linebacker',
    'corner back',
    'safety',
    'kicker',
    'punter',
    'long snapper',
  ],
  basketball: [
    'point guard',
    'shooting guard',
    'small forward',
    'power forward',
    'center',
  ],
  baseball: [
    'pitcher',
    'catcher',
    '1st baseman',
    '2nd baseman',
    '3rd baseman',
    'shortstop',
    'infielder',
    'outfielder',
    'designated hitter',
  ],
  bowling: ['table setter', 'middle', 'setup', 'anchor'],
  cross_country: ['harrier', 'runner'],
  field_hockey: [
    'forward/striker',
    'midfielder',
    'fullback/defender',
    'sweeper',
    'goalie',
  ],
  golf: ['golfer'],
  gymnastics: [
    'acrobat',
    'all  arounder',
    'artistic',
    'power tumbling',
    'rhythmic',
    'trampoline',
  ],
  ice_hockey: ['center', 'winger', 'defensemen', 'goalie'],
  lacrosse: ['attackman', 'midfielder', 'defender', 'goal keeper'],
  rowing: ['coxswain', 'rower'],
  soccer: ['forward', 'midfielder', 'defender', 'goal keeper'],
  softball: [
    'pitcher',
    'catcher',
    '1st baseman',
    '2nd baseman',
    '3rd baseman',
    'shortstop',
    'outfielder',
    'infielder',
  ],
  swimming_diving: ['swimmer', 'diver'],
  tennis: ['tennis player'],
  track_field: ['sprinter', 'distance runner', 'hurdler', 'jumper'],
  volleyball: [
    'outside hitter',
    'middle blocker',
    'opposite hitter',
    'setter',
    'libero',
    'defensive specialist',
    'serving specialist',
  ],
  water_polo: ['goal keeper', 'wing', 'diver', 'point', 'center forward'],
  wrestling: ['wrestler'],
};

export const SPORTS_STATS: any = {
  football: {
    offense: [
      { label: 'Passing Yards', field: 'passing_yards' },
      { label: 'Passing Touchdowns', field: 'passing_touchdowns' },
      { label: 'Completion %', field: 'completion_%' },
      { label: 'Rushing Yards', field: 'rushing_yards' },
      { label: 'Rushing Touchdowns', field: 'rushing_touchdowns' },
      { label: 'Pancakes', field: 'pancakes' },
      { label: 'Receptions', field: 'receptions' },
      { label: 'Receiving Yards', field: 'receiving_yards' },
      { label: 'Receiving Touchdowns', field: 'receiving_touchdowns' },
    ],
    defense: [
      { label: 'Total Tackles', field: 'total_tackles' },
      { label: 'Tackles for Loss', field: 'tackles_for_loss' },
      { label: 'Average Tackles Per Game', field: 'average_tackles_per_game' },
      { label: 'Sacks', field: 'sacks' },
      { label: 'Forced Fumbles', field: 'forced_fumbles' },
      { label: 'Interceptions', field: 'interceptions' },
      { label: 'Passes Defended', field: 'passes_defended' },
      { label: 'Defensive Touchdowns', field: 'defensive_touchdowns' },
    ],
    'Special Teams': [
      { label: 'Kickoff Return Yards', field: 'kickoff_return_yards' },
      {
        label: 'Average Kickoff Return Yards',
        field: 'average_kickoff_return_yards',
      },
      { label: 'Punt Return Yards', field: 'punt_return_yards' },
      {
        label: 'Average Punt Return Yards',
        field: 'average_punt_return_yards',
      },
      {
        label: 'Kickoff Return Touchdowns',
        field: 'kickoff_return_touchdowns',
      },
      { label: 'Punt Return Touchdowns', field: 'punt_return_touchdowns' },
      { label: 'Extra Points Made', field: 'extra_points_made' },
      { label: 'Field Goals Made', field: 'field_goals_made' },
      { label: 'Longest Field Goal', field: 'longest_field_goal' },
      { label: 'Punting Yard Average', field: 'punting_yard_average' },
      { label: 'Longest Punt', field: 'longest_punt' },
      {
        label: 'Blocked Punts/Field Goals',
        field: 'blocked_punts/field_goals',
      },
    ],
  },
  field_hockey: {
    offense: [
      { label: 'Goals', field: 'goals' },
      { label: 'Goals Per Game', field: 'goals_per_game' },
      { label: 'Assists', field: 'assists' },
      { label: 'Assists Per Game', field: 'assists_per_game' },
      { label: 'Points', field: 'points' },
    ],
    defense: [
      { label: 'Defensive Saves', field: 'defensive_saves' },
      { label: 'Goals Against Average', field: 'goals_against_average' },
      { label: 'Saves %', field: 'saves_%' },
      { label: 'Steals', field: 'steals' },
    ],
  },
  basketball: {
    offense: [
      { label: 'Points Per Game', field: 'points_per_game' },
      { label: 'Field Goal %', field: 'field_goal_%' },
      { label: '3 Point %', field: '3_point_%' },
      { label: 'Free Throw %', field: 'free_throw_%' },
      {
        label: 'Offensive Rebounds Per Game',
        field: 'offensive_rebounds_per_game',
      },
      { label: 'Assists Per Game', field: 'assists_per_game' },
    ],
    defense: [
      { label: 'Blocks Per Game', field: 'blocks_per_game' },
      { label: 'Steals Per Game', field: 'steals_per_game' },
      {
        label: 'Defensive Rebounds Per Game',
        field: 'defensive_rebounds_per_game',
      },
    ],
  },
  baseball: {
    offense: [
      { label: 'Batting Average', field: 'batting_average' },
      { label: 'Home Runs', field: 'home_runs' },
      { label: 'Slugging %', field: 'slugging_%' },
      { label: 'RBI', field: 'rbi' },
      {
        label: 'Runs',
        field: 'runs',
      },
      { label: 'On Base %', field: 'on_base_%' },
      { label: 'Stolen Bases', field: 'stolen_bases' },
    ],
    defense: [
      { label: 'ERA', field: 'era' },
      { label: 'Strike Outs', field: 'strike_outs' },
      {
        label: 'No Hitters',
        field: 'no_hitters',
      },
      {
        label: 'Fielding Percentage',
        field: 'fielding_percentage',
      },
    ],
  },
  softball: {
    offense: [
      { label: 'Batting Average', field: 'batting_average' },
      { label: 'Home Runs', field: 'home_runs' },
      { label: 'Slugging %', field: 'slugging_%' },
      { label: 'RBI', field: 'rbi' },
      {
        label: 'Runs',
        field: 'runs',
      },
      { label: 'On Base %', field: 'on_base_%' },
      { label: 'Stolen Bases', field: 'stolen_bases' },
    ],
    defense: [
      { label: 'ERA', field: 'era' },
      { label: 'Strike Outs', field: 'strike_outs' },
      {
        label: 'No Hitters',
        field: 'no_hitters',
      },
      {
        label: 'Fielding Percentage',
        field: 'fielding_percentage',
      },
    ],
  },
  soccer: {
    offense: [
      { label: 'Goals Scored', field: 'goals_scored' },
      { label: 'Assists', field: 'assists' },
      { label: 'Assists Per Game', field: 'assists_per_game' },
      { label: 'Points', field: 'points' },
      { label: 'Points Per Game', field: 'points_per_game' },
      { label: 'Shots On Goal', field: 'shots_on_goal' },
      { label: 'Shots On Goal%', field: 'shots_on_goal_%' },
    ],
    defense: [
      { label: 'Steals', field: 'steals' },
      { label: 'Saves Per Match', field: 'saves_per_match' },
      {
        label: 'Goals Saved',
        field: 'goals_saved',
      },
      { label: 'Saved %', field: 'saved_%' },
      { label: 'Goals Against Average', field: 'goals_against_average' },
    ],
  },
  lacrosse: {
    offense: [
      { label: 'Goals', field: 'goals' },
      { label: 'Assists', field: 'assists' },
      { label: 'Points', field: 'points' },
      { label: 'Points Per Game', field: 'points_per_game' },
      { label: 'Assists Per Game', field: 'assists_per_game' },
      { label: 'Ground Balls Per Game', field: 'ground_balls_per_game' },
      { label: 'Shooting %', field: 'shooting_%' },
    ],
    defense: [
      { label: 'Take Aways', field: 'take_aways' },
      { label: 'Goals Against Average', field: 'goals_against_average' },
      {
        label: 'Goals Allowed',
        field: 'goals_allowed',
      },
      {
        label: 'Goals Saved',
        field: 'goals_saved',
      },
      { label: 'Save %', field: 'save_%' },
      { label: 'Steals', field: 'steals' },
    ],
  },
  track_field: {
    track: [
      { label: '100 Meter', field: '100_meter' },
      { label: '200 Meter', field: '200_meter' },
      { label: '400 Meter', field: '400_meter' },
      { label: '800 Meter', field: '800_meter' },
      { label: '1500 Meter', field: '1500_meter' },
      { label: '1600 Meter', field: '1600_meter' },
      { label: '3000 Meter', field: '3000_meter' },
      { label: '3200 Meter', field: '3200_meter' },
      { label: '5K', field: '5k' },
      { label: '2000 Steeple', field: '2000_steeple' },
      { label: '3000 Steeple', field: '3000_steeple' },
      { label: '100 Meter Hurdles', field: '100_meter_hurdles' },
      { label: '300 Meter Hurdles', field: '300_meter_hurdles' },
      { label: '400 Meter Hurdles', field: '400_meter_hurdles' },
    ],
    field: [
      { label: 'High Jump', field: 'high_jump' },
      { label: 'Long Jump', field: 'long_jump' },
      { label: 'Triple Jump', field: 'triple_jump' },
      { label: 'Pole Volt', field: 'Pole Volt' },
      { label: 'Discus', field: 'discus' },
      { label: 'Hammer', field: 'hammer' },
      { label: 'Javelin', field: 'javelin' },
      { label: 'Shot Put', field: 'shot_put' },
    ],
  },
  volleyball: {
    offense: [
      { label: 'Serving Aces', field: 'serving_aces' },
      { label: 'Aces per Game', field: 'aces_per_game' },
      { label: 'Assists per Game', field: 'assists_per_game' },
      { label: 'Assists', field: 'assists' },
      { label: 'Digs', field: 'digs' },
      { label: 'Digs per Game', field: 'digs_per_game' },
      { label: 'Hitting %', field: 'hitting_%' },
      { label: 'Kills', field: 'kills' },
      { label: 'Kills per Game', field: 'kills_per_game' },
    ],
    defense: [
      { label: 'Blocks per Game', field: 'blocks_per_game' },
      { label: 'Block Assists', field: 'block_assists' },
      { label: 'Solo Blocks', field: 'solo_blocks' },
      { label: 'Total Blocks', field: 'total_blocks' },
    ],
  },
  ice_hockey: {
    offense: [
      { label: 'Points', field: 'points' },
      { label: 'Goals', field: 'goals' },
      { label: 'Assists', field: 'assists' },
      { label: 'Shots on Goal', field: 'shots_on_goal' },
      { label: 'Shooting %', field: 'shooting_%' },
    ],
    defense: [
      { label: 'Saves', field: 'saves' },
      { label: 'Saves %', field: 'saves_%' },
      { label: 'Shut Out Save %', field: 'shut_out_save_%' },
      { label: 'Shots Against', field: 'shots_against' },
      { label: 'Goals Against Average', field: 'goals_agains_average' },
    ],
  },
  tennis: {
    all: [
      { label: 'Aces', field: 'aces' },
      { label: 'Break Points', field: 'break_points' },
      { label: 'Games Won', field: 'games_won' },
      { label: '1st Serve Points Won', field: '1st_serve_points_won' },
      { label: '2nd Serve Points Won', field: '2nd_serve_points_won' },
      { label: 'Points Won', field: 'points_won' },
      { label: 'Win % on 1st Serve', field: 'win_%_on_1st_serve' },
      { label: 'Win % on 2nd Serve', field: 'win_%_on_2nd_serve' },
    ],
  },
  swimming_diving: {
    swimming: [
      { label: '50 Free Time', field: '50_free_time' },
      { label: '100 Fly Time', field: '100_fly_time' },
      { label: '100 Free Time', field: '100_free_time' },
      { label: '100 Back Time', field: '100_back_time' },
      { label: '100 Breast Time', field: '100_breast_time' },
      { label: '200 Free Time', field: '200_free_time' },
      {
        label: '200 Individual Medley Time',
        field: '200_individual_medley_time',
      },
      { label: '500 Free Time', field: '500_free_time' },
      { label: 'One Meter', field: 'one_meter' },
      { label: 'Three Meter', field: 'three_meter' },
      { label: 'Platform 5 Meter', field: 'platform_5_meter' },
      { label: 'Platform 7.5 Meter', field: 'platform_7.5_meter' },
      { label: 'Platform 10 Meter', field: 'platform_10_meter' },
    ],
    diving: [
      { label: 'One Meter Total Points', field: 'one_meter_total_points' },
      { label: 'One Meter Dives', field: 'one_meter_dives' },
      { label: 'Three Meter Total Points', field: 'three_meter_total_points' },
      { label: 'Three Meter Dives', field: 'three_meter_dives' },
      {
        label: 'Platform 5 Meter Total Points',
        field: 'platform_5_meter_total_points',
      },
      { label: 'Platform 5 Meter Dives', field: 'platform_5_meter_dives' },
      {
        label: 'Platform 7.5 Meter Total Points',
        field: 'platform_7.5_meter_total_points',
      },
      { label: 'Platform 7.5 Meter Dives', field: 'platform_7.5_meter_dives' },
      {
        label: 'Platform 10 Meter Total Points',
        field: 'platform_10_meter_total_points',
      },
      { label: 'Platform 10 Meter Dives', field: 'platform_10_meter_dives' },
    ],
  },
  water_polo: {
    offense: [
      { label: 'Points', field: 'points' },
      { label: 'Goals', field: 'goals' },
      { label: 'Goals Per Game', field: 'goals_per_game' },
      { label: 'Assists', field: 'assists' },
      { label: 'Assists Per Game', field: 'assists_per_game' },
    ],
    defense: [
      { label: 'Saves', field: 'saves' },
      { label: 'Shut Outs', field: 'shut_outs' },
      { label: 'Steals', field: 'steals' },
      { label: 'Goals Against Average', field: 'goals_against_average' },
    ],
  },
  bowling: {
    all: [
      { label: 'Bowling Average', field: 'bowling_average' },
      { label: 'Average Tournament Score', field: 'average_tournament_score' },
      { label: 'Field Average', field: 'field_average' },
      { label: 'Average Differential', field: 'average_differential' },
      { label: 'High Score', field: 'high_score' },
    ],
  },
};

export const ATHLETIC_INFO: any = {
  football: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: '40 Yard Dash', field: '40_yard_dash', type: 'text' },
    { label: '5-10-5 Shuttle', field: '5-10-5_Shuttle', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    { label: 'Broad Jump', field: 'broad_jump', type: 'text' },
    { label: 'Max Bench', field: 'max_bench', type: 'text' },
    { label: 'Max Squat', field: 'max_squat', type: 'text' },
  ],
  field_hockey: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: '20m Shuttle Run', field: '20m_shuttle_run', type: 'text' },
    { label: '5-10-5 Shuttle', field: '5-10-5_shuttle', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    { label: 'Max Bench', field: 'max_bench', type: 'text' },
    { label: 'Max Squat', field: 'max_squat', type: 'text' },
  ],
  basketball: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'Wing Span', field: 'wing_span', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    {
      label: 'No Step Vertical Jump',
      field: 'no_step_vertical_jump',
      type: 'text',
    },
    { label: '3/4 Sprint Time', field: '3/4_sprint_time', type: 'text' },
    { label: '20m Sprint Time', field: '20m_sprint_time', type: 'text' },
    { label: 'Lane Agility Time', field: 'lane_agility_time', type: 'text' },
    {
      label: 'Reactive Shuttle Time',
      field: 'reactive_shuttle_time',
      type: 'text',
    },
    { label: 'Max Bench', field: 'max_bench', type: 'text' },
  ],
  baseball: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'Pitch Speed', field: 'pitch_speed', type: 'text' },
    { label: 'Home to 1st Base', field: 'home_to_1st_base', type: 'text' },
    { label: '3 Cone Drill', field: '3_cone_drill', type: 'text' },
    { label: '60 Yard Dash', field: '60_yard_dash', type: 'text' },
    { label: '20 Yard Dash', field: '20_yard_dash', type: 'text' },
    { label: '5-10-5 Shuttle', field: '5-10-5_shuttle', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    { label: 'Broad Jump', field: 'broad_jump', type: 'text' },
    {
      label: 'Rotational Power Ball Throw',
      field: 'rotational_power_ball_throw',
      type: 'text',
    },
    {
      label: 'Medicine Ball Throw',
      field: 'medicine_ball_throw',
      type: 'text',
    },
  ],
  softball: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'Pitch Speed', field: 'pitch_speed', type: 'text' },
    { label: 'Home to 1st Base', field: 'home_to_1st_base', type: 'text' },
    { label: '3 Cone Drill', field: '3_cone_drill', type: 'text' },
    { label: '60 Yard Dash', field: '60_yard_dash', type: 'text' },
    { label: '20 Yard Dash', field: '20_yard_dash', type: 'text' },
    { label: '5-10-5 Shuttle', field: '5-10-5_shuttle', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    { label: 'Broad Jump', field: 'broad_jump', type: 'text' },
    {
      label: 'Rotational Power Ball Throw',
      field: 'rotational_power_ball_throw',
      type: 'text',
    },
    {
      label: 'Medicine Ball Throw',
      field: 'medicine_ball_throw',
      type: 'text',
    },
  ],
  soccer: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: '30m Dash', field: '30m_dash', type: 'text' },
    { label: '5-10-5 Shuttle', field: '5-10-5_shuttle', type: 'text' },
    { label: '505 Agility Test', field: '505_agility_test', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
  ],
  lacrosse: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: '10 Yard Split', field: '10_yard_split', type: 'text' },
    { label: '40 Yard Dash', field: '40_yard_dash', type: 'text' },
    { label: 'Shot Speed', field: 'shot_speed', type: 'text' },
    { label: 'Shuttle Run', field: 'shuttle_run', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    { label: 'Power Ball Toss', field: 'power_ball_toss', type: 'text' },
  ],
  golf: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'Average Score', field: 'average_score', type: 'text' },
    {
      label: 'Fairways in Regulation %',
      field: 'fairways_in_regulation_%',
      type: 'text',
    },
    {
      label: 'Greens in Regulation %',
      field: 'greens_in_regulation_%',
      type: 'text',
    },
    { label: 'Putting Average', field: 'putting_average', type: 'text' },
    { label: 'Handicap', field: 'handicap', type: 'text' },
    {
      label: 'Average Drive Distance',
      field: 'average_drive_distance',
      type: 'text',
    },
    {
      label: 'Tournament Score Differential',
      field: 'tournament_score_differential',
      type: 'text',
    },
  ],
  track_field: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'Max Squat', field: 'max_squat', type: 'text' },
    { label: 'Broad Jump', field: 'broad_jump', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    { label: 'Max Bench', field: 'max_bench', type: 'text' },
  ],
  cross_country: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: '800 Meter Time', field: '800_meter_time', type: 'text' },
    { label: 'Mile Time', field: 'mile_time', type: 'text' },
    { label: '2 Mile Time', field: '2_mile_time', type: 'text' },
    { label: '5K Time', field: '5K_time', type: 'text' },
    { label: '10K Time', field: '10K_time', type: 'text' },
  ],
  volleyball: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'Approach Jump', field: 'approach_jump', type: 'text' },
    { label: 'Broad Jump', field: 'broad_jump', type: 'text' },
    { label: 'Standing Reach', field: 'standing_reach', type: 'text' },
    { label: '5-10-5 Shuttle', field: '5-10-5_shuttle', type: 'text' },
  ],
  wrestling: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'Wing Span', field: 'wing_span', type: 'text' },
    { label: 'Max Bench', field: 'max_bench', type: 'text' },
    { label: 'Dead Lift', field: 'dead_lift', type: 'text' },
    { label: 'Squat', field: 'squat', type: 'text' },
    { label: '1 Mile Time', field: '1_mile_time', type: 'text' },
    { label: '40 Yard Dash', field: '40_yard_dash', type: 'text' },
    { label: '5-10-5 Shuttle', field: '5-10-5_shuttle', type: 'text' },
    { label: 'Record', field: 'record', type: 'text' },
    { label: 'Takedowns', field: 'takedowns', type: 'text' },
    { label: 'Falls', field: 'falls', type: 'text' },
  ],
  rowing: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: '500m Ergo Test', field: '500m_ergo_test', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    { label: 'Strokes Per Minute', field: 'strokes_per_minute', type: 'text' },
    { label: '2K erg Time', field: '2K_erg_time', type: 'text' },
  ],
  ice_hockey: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'Wing Span', field: 'wing_span', type: 'text' },
    { label: 'Wingate Test', field: 'wingate_test', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    { label: 'Broad Jump', field: 'broad_jump', type: 'text' },
    { label: '5-10-5 Shuttle', field: '5-10-5_shuttle', type: 'text' },
    { label: 'Max Bench', field: 'max_bench', type: 'text' },
  ],
  tennis: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: '20m Sprint', field: '20m_sprint', type: 'text' },
    { label: '5-10-5 Shuttle', field: '5-10-5_shuttle', type: 'text' },
    { label: '505 Agility Test', field: '505_agility_test', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
  ],
  swimming_diving: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'V02 Max Test', field: 'V02_max_test', type: 'text' },
    { label: 'Broad Jump', field: 'broad_jump', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
  ],
  gymnastics: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'Gymnastics Level', field: 'gymnastics_level', type: 'text' },
  ],
  water_polo: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'V02 Max Test', field: 'V02_max_test', type: 'text' },
    {
      label: 'Water Vertical Jump',
      field: 'water_vertical_jump',
      type: 'text',
    },
    { label: 'WIST', field: 'WIST', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    { label: 'Bench Press', field: 'bench_press', type: 'text' },
  ],
  bowling: [
    { label: 'Height', field: 'height', required: true },
    { label: 'Weight', field: 'weight', required: true },
    {
      label: 'Highlight Link',
      field: 'highlight_link',
      required: true,
      type: 'text',
    },
    { label: 'Jersey Number', field: 'jersey_number', type: 'text' },
    { label: 'Accolades', field: 'accolades', type: 'text' },
    { label: 'Release RPM', field: 'release_rpm', type: 'text' },
    { label: 'Release Ratio', field: 'release_ratio', type: 'text' },
    { label: 'Broad Jump', field: 'broad_jump', type: 'text' },
    { label: 'Vertical Jump', field: 'vertical_jump', type: 'text' },
    { label: 'Grip Strength', field: 'grip_strength', type: 'text' },
  ],
};

interface CalendarLinks {
  [key: string]: string;
}

export const RECRUITING_CALENDAR_D1: CalendarLinks = {
  'football fbs':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_FBSMFBRecruitingCalendar.pdf',
  'football fcs':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_FCSMFBRecruitingCalendar.pdf',
  'field hockey':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'basketball mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_MBBRecruitingCalendar.pdf',
  'basketball womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_WBBRecruitingCalendar.pdf',
  baseball:
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_MBARecruitingCalendar.pdf',
  softball:
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_WSBRecruitingCalendar.pdf',
  'soccer mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'soccer womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'lacrosse mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_MLARecruitingCalendar.pdf',
  'lacrosse womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_WBBRecruitingCalendar.pdf',
  'golf mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_MGORecruitingCalendar.pdf',
  'golf womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'track & field mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_XTFRRecruitingCalendar.pdf',
  'track & field womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_XTFRRecruitingCalendar.pdf',
  'cross country mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_XTFRRecruitingCalendar.pdf',
  'cross country womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_XTFRRecruitingCalendar.pdf',
  'volleyball mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'volleyball womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_WVBRecruitingCalendar.pdf',
  wrestling:
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  rowing:
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'ice hockey mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'ice hockey womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'tennis mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'tennis womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'swimming & diving mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'swimming & diving womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'gymnastics mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'gymnastics womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'water polo mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'water polo womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
  'bowling womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D1Rec_OtherSportsRecruitingCalendar.pdf',
};

export const RECRUITING_CALENDAR_D2: CalendarLinks = {
  football:
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendar_FB.pdf',
  'field hockey':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'basketball mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendar_MBB.pdf',
  'basketball womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendar_WBB.pdf',
  baseball:
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  softball:
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'soccer mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'soccer womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'lacrosse mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'lacrosse womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'golf mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'golf womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'track & field mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'track & field womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'cross country mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'cross country womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'volleyball mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'volleyball womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  wrestling:
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  rowing:
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'ice hockey mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'ice hockey womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'tennis mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'tennis womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'swimming & diving mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'swimming & diving womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'gymnastics mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'gymnastics womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'water polo mens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'water polo womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
  'bowling womens':
    'https://ncaaorg.s3.amazonaws.com/compliance/recruiting/calendar/2022-23/2022-23D2REC_RecCalendars_SOTFB.pdf',
};

export const PAYMENT_TYPE = [
  { id: '', text: '1 time' },
  { id: 'month', text: 'per month' },
  { id: 'year', text: 'per year' },
];

export const POSITION_MAPPING_BY_SPORT: {
  [sport: string]: { [position: string]: string };
} = {
  football: {
    quarterback: 'QB',
    'running back': 'RB',
    'full back': 'FB',
    'wide receiver': 'WR',
    'tight end': 'TE',
    center: 'C',
    'offensive line': 'OL',
    'left tackle': 'LT',
    'left guard': 'LG',
    'right guard': 'RG',
    'right tackle': 'RT',
    'defensive line': 'DL',
    'defensive end': 'DE',
    'defensive tackle': 'DT',
    linebacker: 'LB',
    'middle linebacker': 'MLB',
    'outside linebacker': 'OLB',
    cornerback: 'CB',
    safety: 'S',
    'free safety': 'FS',
    'strong safety': 'SS',
    kicker: 'K',
    punter: 'P',
    'long snapper': 'LS',
  },
  basketball: {
    'point guard': 'PG',
    'shooting guard': 'SG',
    'small forward': 'SF',
    'power forward': 'PF',
    center: 'C',
  },
  baseball: {
    pitcher: 'P',
    catcher: 'C',
    '1st baseman': '1B',
    '2nd baseman': '2B',
    '3rd baseman': '3B',
    shortstop: 'SS',
    outfielder: 'OF',
    'left fielder': 'LF',
    'center fielder': 'CF',
    'right fielder': 'RF',
    infielder: 'IF',
    'designated hitter': 'DH',
  },
  bowling: {
    'table setter': '',
    middle: '',
    setup: '',
    anchor: '',
  },
  cross_country: {
    harrier: '',
    runner: '',
  },
  field_hockey: {
    'forward/striker': '',
    midfielder: 'M',
    defender: 'D',
    goalie: 'G',
  },
  golf: {
    golfer: '',
  },
  gymnastics: {
    'all around': 'AA',
    vault: 'VT',
    'uneven bars': 'UB',
    'Balance beam': 'BB',
    'floor excercise': 'FX',
    'pommel Horse': 'PH',
    'still rings': 'SR',
    'parallel bars': 'PB',
    'horizontal bars': 'HB',
  },
  ice_hockey: {
    'left wing': 'LW',
    'right wing': 'RW',
    defensemen: 'D',
    goalie: 'G',
    center: 'C',
  },
  lacrosse: {
    attack: 'A',
    defense: 'D',
    'goal keeper': 'G',
    midfiled: 'M',
    'face off specialist': 'FO',
  },
  rowing: {
    coxswain: 'C',
    'stroke seat': 'S',
    'bow seat': 'B',
  },
  soccer: {
    'forward/striker': 'F/S',
    midfielder: 'M',
    defender: 'D',
    goalie: 'G',
    'goal keeper': 'GK',
    'center back': 'CB',
    'full back': 'FB',
    'wing back': 'WB',
    'defensive midfileder': 'DM',
    'central midfielder': 'CM',
    'attacking midfileder': 'AM',
    'right wing': 'RW',
    'left wing': 'LW',
    striker: 'ST',
  },
  softball: {
    pitcher: 'P',
    catcher: 'C',
    '1st baseman': '1B',
    '2nd baseman': '2B',
    '3rd baseman': '3B',
    shortstop: 'SS',
    outfielder: 'OF',
    'left fielder': 'LF',
    'center fileder': 'CF',
    'right fielder': 'RF',
    infielder: 'IF',
  },
  swimming_diving: {
    freestyle: 'FR',
    backstroke: 'BK',
    breaststroke: 'BR',
    butterfly: 'FL',
    'individual medley': 'IM',
    relay: 'R',
    diver: 'D',
  },
  tennis: {
    'singles player': 'S',
    'doubles player': 'D',
  },
  track_field: {
    sprinter: 'SPR',
    'high hurdler': 'HH',
    'low hurdler': 'LH',
    'high jump': 'HJ',
    'low jump': 'LJ',
    'triple jump': 'TJ',
    'pole vault': 'PV',
  },
  volleyball: {
    'outside hitter': 'OH',
    'middle blocker': 'MB',
    'right side hitter': 'RS',
    setter: 'S',
    libero: 'L',
    'defensive specialist': 'DS',
  },
  water_polo: {
    'goal keeper': 'GK',
    'center back': 'CB',
    'center forward': 'CF',
    driver: 'DR',
    'wing defender': 'WD',
    point: 'P',
  },
  wrestling: {
    wrestler: '',
  },
};
